// Generated by scripts/artwork/05-slice.py. Do not edit by hand.
//
// Wide plates cut along their own gutters, for stacking on a phone.

export type PlateTile = { src: string; w: number; h: number };

export const PLATE_TILES: Record<string, PlateTile[]> = {
  "context-en": [
    {
      src: "/artwork/tiles/context-en-1.webp",
      w: 939,
      h: 450
    },
    {
      src: "/artwork/tiles/context-en-2.webp",
      w: 367,
      h: 450
    },
    {
      src: "/artwork/tiles/context-en-3.webp",
      w: 434,
      h: 450
    },
    {
      src: "/artwork/tiles/context-en-4.webp",
      w: 501,
      h: 454
    },
    {
      src: "/artwork/tiles/context-en-5.webp",
      w: 381,
      h: 454
    },
    {
      src: "/artwork/tiles/context-en-6.webp",
      w: 348,
      h: 454
    },
    {
      src: "/artwork/tiles/context-en-7.webp",
      w: 510,
      h: 454
    }
  ],
  "context-fr": [
    {
      src: "/artwork/tiles/context-fr-1.webp",
      w: 939,
      h: 450
    },
    {
      src: "/artwork/tiles/context-fr-2.webp",
      w: 367,
      h: 450
    },
    {
      src: "/artwork/tiles/context-fr-3.webp",
      w: 434,
      h: 450
    },
    {
      src: "/artwork/tiles/context-fr-4.webp",
      w: 501,
      h: 454
    },
    {
      src: "/artwork/tiles/context-fr-5.webp",
      w: 381,
      h: 454
    },
    {
      src: "/artwork/tiles/context-fr-6.webp",
      w: 348,
      h: 454
    },
    {
      src: "/artwork/tiles/context-fr-7.webp",
      w: 510,
      h: 454
    }
  ]
};
