"""Cut the wide plates into their own grid cells, for reading on a phone.

At a 390px viewport a 1740px plate renders at about 20% scale, which puts the
hand lettering at four or five pixels. It is legible on a laptop and useless in
a hand. These plates are drawn on a grid, though, so they can be cut along the
gutters between cells and stacked in reading order instead of shrunk.

The cut lines below were measured off the ink: a column or row of the plate that
carries no ink in either the English or the French drawing. They are shared
between the two locales because the layouts match to within a few pixels, but
they are checked against both before anything is written.

Writes the tiles and a generated manifest the page component reads, so the
coordinates live in exactly one place.
"""
import json, os
import numpy as np
from PIL import Image

SRC, DST = 'artwork/orange', 'client/public/artwork/tiles'
MANIFEST = 'client/src/lib/plate-tiles.ts'
MAXW = 1800

# plate -> (locale sources, [(x0, y0, x1, y1), ...] in reading order)
PLATES = {
    'context': (
        {'en': 'EN-Context', 'fr': 'FR-Context'},
        [(0, 0, 939, 450), (939, 0, 1306, 450), (1306, 0, 1740, 450),
         (0, 450, 501, 904), (501, 450, 882, 904), (882, 450, 1230, 904),
         (1230, 450, 1740, 904)],
    ),
}

def ink_free(img, box):
    """True if the four cut edges of this tile fall on bare paper."""
    a = np.asarray(img.convert('RGB')).astype(np.float32) / 255
    ink = a.mean(2) < 0.72
    x0, y0, x1, y1 = box
    h, w = ink.shape
    for x in (x0, x1):
        if 0 < x < w and ink[y0:y1, max(0, x - 2):x + 2].mean() > 0.004:
            return False
    for y in (y0, y1):
        if 0 < y < h and ink[max(0, y - 2):y + 2, x0:x1].mean() > 0.004:
            return False
    return True

os.makedirs(DST, exist_ok=True)
manifest = {}
for name, (sources, boxes) in PLATES.items():
    for loc, stem in sources.items():
        im = Image.open(os.path.join(SRC, stem + '.png')).convert('RGB')
        entries = []
        for i, box in enumerate(boxes, 1):
            if not ink_free(im, box):
                raise SystemExit(f'{stem}: cut {box} crosses ink — re-measure the gutters')
            tile = im.crop(box)
            if tile.width > MAXW:
                tile = tile.resize((MAXW, round(tile.height * MAXW / tile.width)), Image.LANCZOS)
            out = f'{name}-{loc}-{i}.webp'
            tile.save(os.path.join(DST, out), 'WEBP', quality=84, method=6)
            entries.append({'src': f'/artwork/tiles/{out}', 'w': tile.width, 'h': tile.height})
        manifest[f'{name}-{loc}'] = entries
        print(f'  {name}-{loc}: {len(entries)} tiles, '
              f'{min(e["w"] for e in entries)}-{max(e["w"] for e in entries)}px wide')

with open(MANIFEST, 'w') as f:
    f.write('// Generated by scripts/artwork/05-slice.py. Do not edit by hand.\n')
    f.write('//\n// Wide plates cut along their own gutters, for stacking on a phone.\n\n')
    f.write('export type PlateTile = { src: string; w: number; h: number };\n\n')
    f.write('export const PLATE_TILES: Record<string, PlateTile[]> = ')
    f.write(json.dumps(manifest, indent=2).replace('"src"', 'src').replace('"w"', 'w').replace('"h"', 'h'))
    f.write(';\n')
print(f'  wrote {MANIFEST}')
